# Generated by Django 3.1.1 on 2021-02-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0013_auto_20210204_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default=1, upload_to='profile/%d%m%y'),
            preserve_default=False,
        ),
    ]
