# Generated by Django 3.1.1 on 2021-02-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0014_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(default='', upload_to='profile/%d%m%y'),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.register')),
            ],
        ),
    ]
