# Generated by Django 3.1.1 on 2021-03-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0016_auto_20210226_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlists',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
