# Generated by Django 3.1.1 on 2021-03-26 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0017_wishlists_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('eadd', models.EmailField(max_length=254)),
                ('cnumber', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=100)),
                ('subject', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt', models.CharField(max_length=33)),
                ('added_time1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product_names', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=200)),
                ('product_qun', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.register')),
            ],
        ),
    ]
